Handle enabling/disabling expandrootfs service

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,12 +1,44 @@
 #!/bin/sh
+# postinst script 
+# see: dh_installdeb(1)
 
-if [ -e /etc/init.d/switch_cpu_governor ]; then
-  update-rc.d switch_cpu_governor remove >/dev/null
-fi
+set -e
 
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/raspi-config" ]; then
-	update-rc.d raspi-config defaults >/dev/null || exit $?
-fi
-# End automatically added section
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+
+case "$1" in    
+    configure|upgrade|update|reconfigure)
+	# Do not enable service when in maintenance mode
+	if [ ! -e /etc/systemd/system/multi-user.target.wants/expandrootfs.service.bak ]; then
+	    systemctl enable /etc/systemd/system/expandrootfs.service
+	fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+
+
+exit 0
+
 
